### ISSUE TITLE
Mollie

### ISSUE THREAD

**Issue by bastiaanv** [salvemundi/samu-api#10]
Mollie is ons IDEAL systeem en is van levensbelang voor de website.

@CPP-MASTERRACE, aan jou om dit netjes te implementeren. Neem met mij contact op om een dev key te krijgen. Vergeet niet om het te documenteren in de README file

- [ ] Implementeren
- [ ] Key verwerken in de Env file
- [ ] Documenteren

**Comment by CPP-MASTERRACE** [comment]
https://www.tikkie.me/bedrijven
