### ISSUE TITLE
Swagger documentatie

### ISSUE THREAD

**Issue by bastiaanv** [salvemundi/samu-api#11]
Documentatie is key voor een onderhoudbaar project. Hierom willen we zoveel mogelijk documentatie automatisch laten genereren om de drempel zo laag mogelijk te houden.

@davydehaas98, Aan jou om dit netjes op te zetten. We willen gebruik maken van de Swagger plugin voor NestJS (https://docs.nestjs.com/recipes/swagger). Zorg er ook voor dat alles gedocumenteerd wordt in de wiki

- [x] Implementeren
- [x] Documenteren

**Comment by CPP-MASTERRACE** [comment]
Default swagger provider van nestjs toegevoegd cb01c5ad313925f4787471f37f733c5c3a58c53b.

**Comment by bastiaanv** [comment]
Dit moet alleen nog gedocumenteerd worden in de wiki sectie

**Comment by CPP-MASTERRACE** [comment]
Fixed
