### ISSUE TITLE
Authenticatie backend

### ISSUE THREAD

**Issue by bastiaanv** [salvemundi/samu-api#2]
Iedere call dient een authenticatie fase in te gaan, aangezien we gebruik maken van de oauth service van FHICT kunnen we dit allemaal automatiseren.

@CPP-MASTERRACE, Voor jou de opdracht om dit toe te passen op het project. Ook zouden we graag een rechtensysteem erin willen hebben, die we per user/lid kunnen aanpassen. Graag ook documentatie erbij schrijven in de README

- [x] Implementeren
- [x] Documenteren

**Comment by CPP-MASTERRACE** [comment]
Graag wil ik weten welke vorm van authenticatie jullie willen hebben en daarbij ook direct welke vorm van authorizatie.

**Comment by niekvangogh** [comment]
> Graag wil ik weten welke vorm van authenticatie jullie willen hebben en daarbij ook direct welke vorm van authorizatie.

Wat bedoel je? Welke keuzes hebben we?

**Comment by CPP-MASTERRACE** [comment]
Denk je zelf dat het zo duidelijk is ofzo?

**Comment by niekvangogh** [comment]
Nee, maar waar zit jij aan te denken?
