### ISSUE TITLE
[Discussie] Database Diagram

### ISSUE THREAD

**Issue by niekvangogh** [salvemundi/samu-api#27]
Graag hier de discussie van wat iedereen vindt van het Database Diagram.

![image](https://user-images.githubusercontent.com/31407144/64677945-d965c400-d478-11e9-852a-e73753a41428.png)

**Comment by niekvangogh** [comment]
Wat wordt er bedoeld met paid_by in membership?

**Comment by davydehaas98** [comment]
Paid_by wil zeggen dat we de naam van de bankrekeninghouder erin zetten, dus als ik het bijvoorbeeld voor jou betaal staat er DJC de Haas of wat je naam ook is van je rekening. Maar we kunnen er ook iets van een transactie code in zetten om terug te kunnen kijken welke betaling bij welk lidmaatschap hoort? Of helemaal niks. Ik weet namelijk niet wat we willen doen als het gaat om recorden van betalingen in de website of dat we dat gwn via een andere tooling zoals mollie ofzo doen.
