### ISSUE TITLE
E-mail in broncode

### ISSUE THREAD

**Issue by MaxKorlaar** [salvemundi/samu-api#29]
Gezellig wel, maar denk niet dat mensen je zo gaan mailen
https://github.com/salvemundi/samu-api/blob/729b7aa757450f49ef226de7f4630ea217dca555/src/controllers/authorization/authorization.controller.ts#L14

**Comment by MaxKorlaar** [comment]
@davydehaas98

**Comment by bastiaanv** [comment]
Beste Max,

Dankje wel voor je melding! We hebben het aangepast en zullen er beter op letten.

Met vriendelijke groet,
ICT-commissiee
