### ISSUE TITLE
TypeORM

### ISSUE THREAD

**Issue by bastiaanv** [salvemundi/samu-api#3]
Om alle database spul zo makkelijk mogelijk af te handelen, is er gekozen om gebruikt te maken van een ORM, specifieker: TypeORM.

@bastiaanv, Deze moet geïmplementeerd worden met degelijke documentatie in de readme zodat iedereen zijn eigen database eraan kan hangen

- [x] TypeORM implementeren
- [x] Documentatie schrijven in de wiki

**Comment by CPP-MASTERRACE** [comment]
TypeORM is geïmplementeerd: d7d975693dfeba015601807d32b341dbc761661b met een mooie environment file.

**Comment by CPP-MASTERRACE** [comment]
Documentatie staat nu op de wiki [https://github.com/salvemundi/samu-api/wiki/De-environment-file](url)

**Comment by bastiaanv** [comment]
Volledig geïmplementeerd en documentatie is geschreven. Issue kan gesloten worden
