### ISSUE TITLE
Mail service

### ISSUE THREAD

**Issue by bastiaanv** [salvemundi/samu-api#4]
Salve Mundi doet redelijk wat via de mail en we voorzien dat het mail gebruik alleen maar gaat toenemen. Nu maken we gebruik van SendGrid. Dit is een vrij dure oplossing en is niet altijd even betrouwbaar...

@davydehaas98, Voor jou de opdracht om te onderzoeken of wij zelf een mailservice kunnen maken. Ik heb gezien dat dit wel mogelijk is, maar heb er niet heel goed onderzoek naar gedaan. Een van deze mogelijkheden is: SimpleSMTP (https://github.com/andris9/simplesmtp)

Indien het niet mogelijk is, moet SendGrid weer geïmplementeerd worden. Ik kan je de gegevens aanleveren, indien nodig.

Ook willen we graag voorkomen dat tijdens de development rare dingen gebeuren met deze mailservice. Hierom willen we een mailtrap systeem er omheen bouwen, dat inactief is op de productie server, maar voor de rest altijd actief. Dit ook verwerken in de environment file. Een voorbeeld van zo'n soort service is: https://mailtrap.io/

- [ ] Onderzoek doen naar een eigen mailservice
- [ ] Een eigen mailservice maken of SendGrid implementeren
- [ ] Mailtrap implementeren
- [ ] Documenteren hoe de mailservice/sendgrid gebruikt kan worden in de wiki

**Comment by CPP-MASTERRACE** [comment]
https://github.com/nest-modules/mailer Een module met een simpele template engine zodat alles mooi overzichtelijk blijft. 

Simplesmtp heeft al vijf jaar geen commit gehad en wordt in alle waarschijnlijkheid niet meer gemaintained. 

Mocht dat alles niet goed zijn kunnen we nog altijd nodemailer [gebruiken](https://nodemailer.com/about/).
