### ISSUE TITLE
Environment file

### ISSUE THREAD

**Issue by bastiaanv** [salvemundi/samu-api#6]
Omdat we niet alle gevoelige data openbaar willen hebben, dient er een environment file systeem geïmplementeerd te worden.

@CPP-MASTERRACE, aan jou de eer om dit op te zetten en te documenteren in de README file

- [x] Implementeren
- [x] Documenteren

**Comment by CPP-MASTERRACE** [comment]
ocumentatie staat nu op de wiki https://github.com/salvemundi/samu-api/wiki/De-environment-file

**Comment by bastiaanv** [comment]
Graag de documentatie in het engels

**Comment by CPP-MASTERRACE** [comment]
Done
