### ISSUE TITLE
Info pagina's CRUD

### ISSUE THREAD

**Issue by bastiaanv** [salvemundi/samu-api#7]
Iedere commissie wilt graag zijn eigen plekje hebben op de website. Omdat we van te voren niet kunnen bedenken welke er allemaal komen en gaan, gaan we dit op een dynamische manier doen.

@Taco219, Aan jou om dit aan de backend netjes op te zetten. Hierbij moet je denken aan de standaard CRUD operaties waarbij je gebruik maakt van TypeORM en DTO's (Data Transfer Object). Voorbeelden is in het project zelf te vinden.

Dit alles dient ook getest te worden voordat het gemerged kan worden. Voor de testen, maak gebruik van de ingebouwde testing tooling van NestJS (https://docs.nestjs.com/fundamentals/testing) en plaats alle testen in de .spec.ts file.

Als laatste moet iedere call gedocumenteerd worden. Dit wordt automatisch gedaan door de swagger plugin voor NestJS (https://docs.nestjs.com/recipes/swagger). Maar hiervoor dient wel de DTO's correct gedocumenteerd te worden, vergeet dit niet

- [x] InfoPageController aanmaken (als je een betere naam hebt, graag)
- [x] CRUD toepassen
- [x] DTO's schrijven en documenteren
- [x] Testen schrijven

**Comment by thijs** [comment]
@thijs op github is niet de thijs die je denkt dat het is.

**Comment by CPP-MASTERRACE** [comment]
> InfoPageController aanmaken (als je een betere naam hebt, graag)

Kunnen we toch gewoon CommissionController noemen omdat het hier om elke commissie gaat?

**Comment by CPP-MASTERRACE** [comment]
Dus alle CRUD is tot nu toe nog simpel toegepast zonder gekoppelde leden.
